apiVersion: v1
description: Web Application firewall (WAF) as a container to protect other containers. Test 2 Version.
home: https://www.airlock.com
keywords:
- WAF
- Web Application Firewall
- Airlock
- MicroGateway
- Security
- Filtering
maintainers:
- email: support@airlock.com
  name: Airlock
name: microgateway2
version: 0.4.0
appVersion: 1.0
