apiVersion: v1
description: Web Application firewall (WAF) as a container to protect other containers.
home: https://www.airlock.com
keywords:
- WAF
- Web Application Firewall
- Airlock
- MicroGateway
- Security
- Filtering
maintainers:
- email: support@airlock.com
  name: Airlock
name: microgateway
version: 0.3.9
appVersion: 7.4
