{{- $config := .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "microgateway.fullname" . }}
  labels:
    {{- include "microgateway.labels" . | nindent 4 }}
data:
{{- if not $config.dsl }}
  config.yaml: |
    license_file: /secret/config/license
    session:
      encryption_passphrase_file: /secret/config/passphrase
    {{- if .Values.redis.enabled }}
      redis_hosts:
        - {{ $config.redisService }}
    {{- end }}
    log:
      level: {{ $config.logLevel }}

  {{- if $config.useIPFromHeader.enabled }}
    expert_settings:
      apache: |
        RemoteIPHeader {{ $config.useIPFromHeader.header }}
        {{- range $config.useIPFromHeader.trustedProxies }}
        RemoteIPInternalProxy {{ . }}
        {{- end }}
        {{- with $config.expert.apache }}
          {{- . | nindent 8 }}
        {{- end }}
    {{- with $config.expert.security_gate }}
      security_gate: |
        {{- . | nindent 8 }}
    {{- end }}
  {{- end }}

  {{- with $config.apps }}
    apps: {{ . | toYaml | nindent 4 }}
  {{- else }}
    apps:
    - mappings:
      - entry_path: {{ $config.default.mapping.entryPath }}
        session_handling: {{ $config.default.mapping.sessionHandling }}
        deny_rules:
        - enable: {{ $config.default.mapping.denyRules.enabled }}
          log_only: {{ $config.default.mapping.denyRules.logOnly }}
          level: {{ $config.default.mapping.denyRules.level }}
      backend:
        hostname: {{ $config.default.backend.service }}
        port: {{ $config.default.backend.port }}
        protocol: {{ $config.default.backend.protocol }}
    {{- if $config.tlsSecretName }}
      virtual_host:
        certificate:
          certificate_file: /secret/tls/tls.crt
          privatekey_file: /secret/tls/tls.key
          ca_chain_file: /secret/tls/ca.crt
    {{- end }}
  {{- end }}
{{- else }}
  config.yaml: |{{ toYaml $config.dsl | nindent 4 }}
{{- end }}
